import LocalizedStrings from 'react-native-localization';
let Strings = new LocalizedStrings({
  en: {
    langID: '1',
    appname: 'Skip',
    Home: 'Home',
    Login: 'Login',
    Logout: 'Logout',
    Show: 'SHOW MORE',
    ShowLess: 'SHOW LESS',
    ourMenu: 'Our menu',
    Skip: 'Skip',
    facebook: 'Continue with Facebook',
    SignUp: 'Sign up with Email',
    SignNow: 'Sign up now'.toUpperCase(),
    loginSkip: "By continuing, you agree to Skip's",
    loginText: "Good to see you. Let's Skip to the fun bits",
    Email: 'Email',
    Password: 'Password',
    LoginButton: "login, i'm hungary".toUpperCase(),
    forgetPassword: 'Forgot your magic, very secret password?',
    DontHaveAccount: "Don't have an account?",
    Signup: 'Signup',
    Name: 'Name',
    phone: 'Mobile Phone',
    SignUpText: 'Stop waiting, start skipping',
    CreateAccount: 'Create an Account'.toUpperCase(),
    AlreadyHave: 'Already have an account ?',
    Iagree: 'I agree to',
    Terms: 'Terms & Conditions',
    Explore: 'Explore',
    MySkip: 'Orders',
    Current: 'Current Location',
    SearchBy: 'Search nearby Venues',
    Popualr: 'Popular near you',
    Closed: 'Closed'.toUpperCase(),
    Free: 'Free',
    VenueFeat: 'Venue Features',
    VenueCategories: 'Venue Categories',
    SocialMedia: 'Social Media',
    pickVenue: 'Pick Your Venue',
    SearchVenue: 'Search a Venue Name',
    VenuesNear: 'Venues near me',
    History: 'History',
    Favourites: 'Favourites',
    Regulars: 'Regulars',
    Loyalty: 'Loyalty',
    Messages: 'Messages',
    Addorder: 'Add to order',
    ExtraHot: 'Extra Hot',
    SpecialInst: 'Special instructions',
    AddNote: 'Add a note to this item',
    Quantity: 'Quantity',
    ViewOrder: 'View Order',
    Comments: 'Comments'.toUpperCase(),
    Apply: 'Apply',
    Total: 'Total',
    TotalEarning: 'Total Earning',
    OrderMore: 'Order More',
    confirm: 'Confirm',
    lognorReg: 'Login or Register',
    help: 'Help',
    terms: 'T&Cs',
    Profile: 'Profile',
    profileDetails: 'Profile Details',
    InfoForVenues: 'Info for Venues',
    whatisSkip: 'What is Skip?',
    requestCall: 'request a call back'.toUpperCase(),
    cancel: 'Cancel',
    save: 'Save',
    ChangePass: 'Change Password',
    profileDetails: 'Profile Details',
    Name: 'Name'.toUpperCase(),
    Email: 'Email'.toUpperCase(),
    Phone: 'Phone'.toUpperCase(),
    paymentMethod: 'My Payments Methods',
    ChangePass: 'Change Password',
    update: 'Update',
    MyVouchers: 'My Vouchers',
    Invitefriends: 'Invite friends',
    forgetPass: 'Forgot your password?',
    close: 'Close',
    add: 'Add',
    payment: 'Payment',
    PaymentMethod: 'Payment Methods',
    AddCreditCard: 'Add Credit Card',
    AddCard: 'Add Card',
    NewToSkip: 'New on Skip',
    SpecialOffer: 'Special Offers',
    newVendor: 'New Vendor',
    VendorText:
      ' Fill in the form below to become our partner and increase your revenue!',
    workHours: 'Working Hours',
    from: 'from',
    facebook: 'facebook',
    instegram: 'instagram',
    to: 'to',
    location: 'location',
    Confirmation: 'Confirmation Message',
    VendorEnName: 'Vendor English Name',
    VendorArName: 'Vendor Arabic Name',
    VendorEmail: 'Vendor Email',
    VenueFeatures: 'Vendor Features',
    AddImage: 'Add Image',
    CreateVendor: 'Create a Vendor'.toUpperCase(),
    VendorPhone: 'Vendor Phone Number',
    Website: 'Website',
    DontHaveVendor: 'Dont Have A Vendor ?',
    WelcomeTitle:
      'Welcome to skip Vendor first you need to add items to you Menu',
    AddToMenu: 'Add To Menu',
    AddMore: 'Add More',
    Next: 'Next',
    Done: 'Done',
    Back: 'Back',
    selectCat: 'Please Select the Item Category',
    youNeedSelect: 'you need to select a category',
    FillData: 'Please fill the Product data',
    productSpecs: 'Add Product Specs',
    itemName: 'item name:',
    SelectSizes: 'Select Sizes:',
    SelectPrices: 'Select Prices:',
    NewOrders: 'New Orders',
    AcceptedOrders: 'Accepted Orders',
    CompletedOrders: 'Completed Orders',
    CurrentOrders: 'Current Orders Orders',
    pendingCustomer: 'Pending Customer Orders',
    UserName: 'Name',
    UserPhone: 'Phone',
    DelivaryDate: 'Date',
    items: 'Items',
    time: 'Time',
    OrderNumber: 'Order Number #',
    Status: 'Status',
    Delivaryaddress: 'Delivary address',
    OrderSummary: 'Order Summary',
    PreparingOrders: 'Preparing Orders',
    ManageMyStore: 'Manage My Store',
    Saturday: 'Saturday',
    SunToTh: 'Sunday - Thursday',
    CompleteForm: 'Please Complete The Form',
    InvalidEmail: 'Invalid email address',
    InvalidPhone: 'Please enter valid phone number',
    InvalidName: 'username should not be less than 2 character ',
    InvalidPassword: 'password should not be less than 6 character ',
    AcceptTems: 'You need to agree for the terms and conditions',
    UserExist: 'User already exist',
    WrongUser: 'Wrong Email or password',
    ErrorMsg: 'Something went Wrong plase try again...',
    ProductArName: 'Product Arabic Name:',
    ProductEnName: 'Product English Name:',
    arabicDesc: 'Arabic Description',
    englishDesc: 'English Description',
    Price: 'Price',
    SpecInfo: 'Spec Info',
    Rank: 'Rank',
    SpecOptions: 'Spec Options',
    AddSpec: 'Add Spec',
    ProductAdded: 'Product have been added Successfully',
    deleteText: 'Are you sure you want to delete this Product ?',
    Delete: 'Delete',
    Yes: 'Yes',
    or: 'or',
    and: 'and',
    privacy: 'Privacy Policy',
    newDriver: 'New Driver',
    DriverSecurity: 'Driver Security Info',
    resident: 'resident',
    citizen: 'citizen',
    number: 'number',
    numResident: 'Residency number',
    numCitizen: 'National number',
    DriverInfo: 'Driver Info',
    DriverDOB: 'Driver DOB',
    DriverPhotos: 'Driver Photos',
    fillNumCitizen: 'please fill the citizenship number',
    fillNumResident: 'please fill the resident number',
    licensePhoto: 'driving license Photo',
    formPhoto: 'form Photo',
    inCarPhoto: 'Interior photo of a car',
    outCarPhoto: 'Exterior photo of a car',
    send: 'Send',
    ThankYouForRegister: 'Thank You For Your Registration !',
    contactYouSoon: 'we will contact you soon to complete you registration',
    driverText: 'Drive with Skip, Make money on your schedule',
    DriverSignUpMessage: 'Please make sure you entered correct data',
    DriverisNotActive: 'Your account has not been activated yet',
    becomeActive: 'Become Active',
    becomeInActive: 'Become InActive',
    newRequest: 'New Request'.toUpperCase(),
    Accept: 'Accept',
    GotOrder: 'Got The Order',
    Reject: 'Reject',
    Support: 'Support',
    GetDirection: 'Get Direction',
    arrived: 'Arrived',
    Complete: 'Complete',
    DriverSecurity: 'Driver SecurityInfo',
    DriverInfo: 'Driver Info',
    DriverPhotos: 'Driver Photos',
    OpenCamera: 'Open Camera',
    MyOrders: 'My Orders',
    ChooseLibrary: 'Choose From Library',
    alreadyExsist: 'is already exist',
    enableLocation: 'You have to enable location services',
    orderTotal: 'Order Total',
    distance: 'Distance',
    Earning: 'Earning :',
    TotalRejected: 'Total\nRejected',
    TotalAccepted: 'Total\nAccepted',
    TotalOrders: 'Total\nOrders',
    Ok: 'Ok',
    Cancel: 'Cancel',
  },
  ar: {
    langID: '2',
    appname: 'Skip',
    Home: 'الصفحة الرئيسية',
    ourMenu: 'القائمة',
    Login: 'تسجيل الدخول',
    DriverSecurity: 'المعلومات الأمنية',
    DriverPhotos: 'وثائق والصور',
    DriverInfo: 'معلومات الشخصية',
    Skip: 'تخطي',
    Terms: 'الشروط والأحكام',
    facebook: 'متابعة من خلال الفيس بوك',
    SignUp: 'تسجيل الحساب بستخدام البريد الإلكتروني',
    loginText: 'تسرني رؤيتك. دعنا ننتقل إلى الجزء المرح',
    Email: 'البريد الإلكتروني',
    Password: 'كلمة المرور',
    LoginButton: 'تسجيل الدخول ، أنا جائع',
    forgetPassword: 'هل نسيت كلمة المرور السرية الخاصة بك؟',
    DontHaveAccount: 'لا تمتلك حساب',
    Signup: 'سجل',
    Name: 'الإسم',
    loginSkip: ' بالمتابعة ، فإنك توافق على سكيب ',
    phone: 'رقم الهاتف',
    SignUpText: 'توقف عن الانتظار ، ابدأ في التخطي',
    CreateAccount: 'عمل حاساب جديد',
    AlreadyHave: 'هل لديك حساب ؟',
    Iagree: 'انا أوافق على',
    Explore: 'Explore',
    MySkip: 'My Skip',
    Current: 'الموقع الحالي',
    SearchBy: 'Search nearby Venues',
    Popualr: 'Popular near you',
    Closed: 'مغلق',
    Free: 'مجاني',
    Show: 'عرض المزيد',
    Confirmation: 'رسالة تأكيد',
    VenueFeat: 'ميزات المكان',
    VenueCategories: 'فئات المحل',
    SocialMedia: 'منصات التواصل الاجتماعي',
    pickVenue: 'اختيار مكانك',
    History: 'History',
    Favourites: 'Favourites',
    Regulars: 'Regulars',
    Loyalty: 'Loyalty',
    Messages: 'الرسائل',
    Addorder: 'اضافة الى الطلب',
    ExtraHot: 'Extra Hot',
    SpecialInst: 'ملاحطات',
    AddNote: 'إضافة ملاحظة على الطلب',
    Quantity: 'الكمية',
    ViewOrder: 'مشاهدة الطلب',
    Comments: 'ملاحظات',
    Apply: 'تقديم',
    Total: 'المجموع',
    confirm: 'تأكيد الطلب',
    OrderMore: 'طلب المزيد',
    lognorReg: 'تسجيل الدخول او انشاء حساب',
    help: 'مساعدة',
    terms: 'الشروط والاحكام',
    InfoForVenues: 'معلومات الأماكن',
    whatisSkip: 'ما هو سكيب؟',
    SignNow: 'سجل الأن',
    requestCall: 'طلب اتصال',
    Profile: 'الملف الشخصي',
    Logout: 'تسجيل الخروج',
    profileDetails: 'معلومات الملف الشخصي',
    cancel: 'إلغاء',
    save: 'حفظ',
    ChangePass: 'تغير كلمة المرور',
    Name: 'الأسم',
    Email: 'البريد الاكتروني',
    Phone: 'رقم الهاتف',
    paymentMethod: 'طرق الدفع',
    ChangePass: 'تغير كلمة المرور',
    update: 'تعديل',
    forgetPass: 'هل نسيت كلمة المرور؟',
    close: 'اغلاق',
    add: 'اضافة',
    payment: 'الدفع',
    PaymentMethod: 'طرق الدفع',
    AddCreditCard: 'اضافة بطافة إئتمانية',
    AddCard: 'إضافة بطاقة',
    NewToSkip: 'جديد على سكيب',
    SpecialOffer: 'عروض مميزة',
    newVendor: 'بائع جديد',
    VendorText: 'املأ النموذج أدناه لتصبح شريكنا وتزيادة من أرباحك!',
    workHours: 'ساعات العمل',
    from: 'من',
    to: 'إلى',
    facebook: 'فيسبوك',
    instegram: 'انستاجرام',
    location: 'المكان',
    VenueFeatures: 'Venue Features',
    AddImage: 'إضافة صورة',
    CreateVendor: 'انشاء عميل جديد',
    VendorArName: 'اسم المحل بالعربي',
    VendorEnName: 'اسم المحل بالانجلزي',
    VendorEmail: 'البريد الإلكتروني للمحل',
    VendorPhone: 'رقم هاتف المحل',
    Website: 'الموقع الإلكتروني',
    DontHaveVendor: 'لا تمتلك حساب',
    WelcomeTitle:
      'مرحبًا بك في سكيب أولاً عليك إضافة المنتجات إلى القائمة الخاصة بك',
    AddToMenu: 'اضافة إلى القائمة',
    Next: 'التالي',
    Back: 'رجوع',
    selectCat: 'يرجى تحديد فئة العنصر',
    youNeedSelect: 'عليك تحديد الفئة',
    FillData: 'يرجى ملء بيانات المنتج',
    itemName: 'اسم المنتج',
    SelectSizes: 'الأحجام',
    Done: 'تم',
    SelectPrices: 'الأسعار',
    NewOrders: 'الطلبات الجديدة',
    AcceptedOrders: 'الطلبات المقبولة',
    CompletedOrders: 'الطلبات المنجزة',
    CurrentOrders: 'الطلبات الحالية',
    PreparingOrders: 'الطلبات قيد التنفيذ',
    pendingCustomer: 'Pending Customer',
    UserName: 'الأسم',
    UserPhone: 'الهاتف',
    DelivaryDate: 'التاريخ',
    items: 'المنتجات',
    Status: 'الحالة',
    time: 'الوقت',
    OrderNumber: 'رقم الطلب #',
    Delivaryaddress: 'عنوان التوصيل',
    OrderSummary: 'ملخص الطلب',
    ManageMyStore: 'إدارة متجري',
    Saturday: 'السبت',
    SunToTh: 'الأحد - الخميس',
    CompleteForm: 'الرجاء تعبئة جميع الحقول',
    InvalidEmail: 'عنوان البريد الإلكتروني غير صالح',
    InvalidPhone: 'الرجاء ادخال رقم هاتف صحيح',
    InvalidName: 'يجب ان لايقل اسم المستخدم عن حرفين',
    InvalidPassword: 'يجب ان لاتقل كلمة المرور عن ستة احرف',
    AcceptTems: 'عليك الموافقة على الشروط والأحكام',
    WrongUser: 'خطأ في اسم المتخدم او كلمة المرور',
    ErrorMsg: 'حدث خلل ما يرجى المحاول مجددا',
    ProductArName: 'أسم المنتج بالعربية',
    ProductEnName: 'أسم المنتج بالأنجليزية',
    arabicDesc: 'الوصف بالعربية',
    englishDesc: 'الوصف بالانجليزية',
    Price: 'السعر',
    productSpecs: 'اضافة خصائص المنتج',
    SpecInfo: 'معلومات الخاصية',
    Rank: 'الترتيب',
    SpecOptions: 'خيارات',
    AddSpec: 'اضافة خاصية',
    AddMore: 'اضافة المزيد',
    ProductAdded: 'تم اضافة المنتج بنجاح',
    deleteText: 'هل تريد حذف هذا المنتج ؟',
    Delete: 'حذف',
    Yes: 'نعم',
    or: 'أو',
    and: 'و',
    privacy: ' حقوق الملكية ',
    newDriver: 'سائق جديد',
    resident: 'مقيم',
    citizen: 'مواطن',
    number: 'رقم',
    numResident: 'رقم الإقامة',
    numCitizen: 'الرقم الوطني',
    DriverInfo: 'معلومات الساثق',
    DriverSecurity: 'الوثائق الحكومية للسائق',
    DriverDOB: 'تاريخ ميلاد السائق',
    fillNumCitizen: 'عليك تعبئة الرقم الوطني',
    fillNumResident: 'عليك تعبئة الرقم الإقامة',
    DriverPhotos: 'صور السائق',
    licensePhoto: 'صورة عن رخصة القيادة',
    formPhoto: 'صورة من الإستمارة',
    inCarPhoto: 'صورة داخلية لسيارة',
    outCarPhoto: 'صورة خارجية لسيارة',
    send: 'إرسال',
    ThankYouForRegister: 'شكرا لك على تسجيلك معنا',
    contactYouSoon: 'سنتواصل معك قريبا لإتمام عملية التسجيل',
    driverText: 'سجل كسائق لدى سكيب وقم بكسب المال الإضافي',
    DriverSignUpMessage: 'تأكد من ان المعلومات المدخلة صحيحة',
    DriverisNotActive: 'لم يتم تفعيل هذا الحساب بعد',
    becomeActive: 'متاح',
    becomeInActive: 'غير متاح',
    newRequest: 'طلب جديد',
    Accept: 'موافقة',
    Reject: 'رفض',
    GotOrder: 'استلمت الطلب',
    Support: 'ساعدة',
    GetDirection: 'الإتجاهات',
    arrived: 'وصلت',
    Complete: 'تم التسليم',
    OpenCamera: 'فتح الكاميرا',
    ChooseLibrary: 'اختيار من الصور',
    alreadyExsist: 'موجود مسبقا',
    enableLocation: 'عليك تفعيل الموقع',
    orderTotal: 'المجموع',
    distance: 'المسافة',
    TotalRejected: 'مجموع\nالمرفوض',
    TotalAccepted: 'مجموع\nالمقبول',
    TotalOrders: 'مجموع\nالطلبات',
    Earning: 'الكسب',
    TotalEarning: 'مجموع الأرباح',
    Ok: 'نعم',
    Cancel: 'لا',
  },
});
export default Strings;
